/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingPackage;
import backEnd.*;
import frontEnd.BookStoreApp;
/**
 *
 * @author Julian
 */
public class Checkout extends javax.swing.JPanel {

    /**
     * Creates new form Checkout
     */
    public Checkout(BookStoreApp app) {
        initComponents();
        this.app = app;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        bottom = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        middle = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        title.setPreferredSize(new java.awt.Dimension(402, 20));
        title.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bookstore Application v1 - Checkout Summary");
        title.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(title, java.awt.BorderLayout.PAGE_START);

        content.setLayout(new java.awt.BorderLayout());

        top.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        top.setPreferredSize(new java.awt.Dimension(1000, 258));

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        content.add(top, java.awt.BorderLayout.PAGE_START);

        bottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bottom.setPreferredSize(new java.awt.Dimension(1000, 258));
        bottom.setLayout(new java.awt.BorderLayout());

        logout.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        logout.setText("Logout");
        bottom.add(logout, java.awt.BorderLayout.CENTER);

        content.add(bottom, java.awt.BorderLayout.PAGE_END);

        middle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        middle.setPreferredSize(new java.awt.Dimension(1000, 258));

        javax.swing.GroupLayout middleLayout = new javax.swing.GroupLayout(middle);
        middle.setLayout(middleLayout);
        middleLayout.setHorizontalGroup(
            middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        middleLayout.setVerticalGroup(
            middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        content.add(middle, java.awt.BorderLayout.CENTER);

        add(content, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaratation - Manually created
    private BookStoreApp app;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel middle;
    private javax.swing.JPanel title;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
