/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingPackage;
import backEnd.*;
import frontEnd.BookStoreApp;
import java.util.ArrayList;



/**
 *
 * @author Julian
 */
public class CustomerHomePanel extends javax.swing.JPanel {

    
    
    
    /**
     * Creates new form CustomerHomePanel
     */
    public CustomerHomePanel(BookStoreApp app) {
        initComponents();
        this.app = app;
        refreshTable();
        refreshStatus();
    }
    
    private void refreshTable(){
        books = BookManager.getBooks();
        
        javax.swing.table.DefaultTableModel model = 
                   (javax.swing.table.DefaultTableModel) bookTable.getModel();
        
        // Clear old rows
        model.setRowCount(0);
        
        
        
        for (Book book : books){
            model.addRow(new Object[]{
                book.getName(),
                book.getPrice(),
                false
            });
        }
        
        
    }
    
    public void refreshStatus(){
        Customer customer = UserManager.getCustomer();
        usrName.setText("Welcome " + customer.getName() + ".");
        System.out.println("DEBUG: "+ customer.getName());
        usrPoints.setText("You have " + customer.getPoints()+ " points.");
        usrStatus.setText("Your status is " + customer.getStatus() +".");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        usrName = new javax.swing.JLabel();
        usrPoints = new javax.swing.JLabel();
        usrStatus = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        buy = new javax.swing.JButton();
        buyPoints = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        middle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new java.awt.BorderLayout());

        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        title.setPreferredSize(new java.awt.Dimension(402, 20));
        title.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bookstore Application v1 - Customer Home");
        title.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(title, java.awt.BorderLayout.PAGE_START);

        content.setLayout(new java.awt.BorderLayout());

        top.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        top.setPreferredSize(new java.awt.Dimension(1000, 258));
        top.setLayout(new java.awt.GridBagLayout());

        usrName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usrName.setText("Welcome (USER).");
        top.add(usrName, new java.awt.GridBagConstraints());

        usrPoints.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usrPoints.setText("You have # points.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        top.add(usrPoints, gridBagConstraints);

        usrStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usrStatus.setText("Your Status is (STATUS)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        top.add(usrStatus, gridBagConstraints);

        content.add(top, java.awt.BorderLayout.PAGE_START);

        bottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bottom.setPreferredSize(new java.awt.Dimension(1000, 258));
        bottom.setLayout(new java.awt.GridBagLayout());

        buy.setText("Buy Selected books");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });
        bottom.add(buy, new java.awt.GridBagConstraints());

        buyPoints.setText("Buy Selected Books with Points");
        buyPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPointsActionPerformed(evt);
            }
        });
        bottom.add(buyPoints, new java.awt.GridBagConstraints());

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        bottom.add(logout, new java.awt.GridBagConstraints());

        content.add(bottom, java.awt.BorderLayout.PAGE_END);

        middle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        middle.setLayout(new java.awt.BorderLayout());

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Price", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);

        middle.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        content.add(middle, java.awt.BorderLayout.CENTER);

        add(content, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buyPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyPointsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        app.showLogin();
        UserManager.logout();
    }//GEN-LAST:event_logoutActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        BookManager.setShoppingCart(getSelectedBooks());
    }//GEN-LAST:event_buyActionPerformed

    
    
    
    private String[] getSelectedBooks(){
        ArrayList<String> selBooks = new ArrayList<>();
        
        // set table reference
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) bookTable.getModel();
        
        for (int i = 0;i< model.getRowCount(); i++){
            boolean checked = (boolean) model.getValueAt(i,2);
            
            if (checked){
                String name = model.getValueAt(i,0).toString();
                selBooks.add(name);
            }
        
        }
        
        
        
        return selBooks.toArray(new String[0]);
    }
           
            
            


    
    
    // Variables declaratation - Manually created
    private ArrayList<Book> books;
    private BookStoreApp app;
    String[] cartBooks;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookTable;
    private javax.swing.JPanel bottom;
    private javax.swing.JButton buy;
    private javax.swing.JButton buyPoints;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel middle;
    private javax.swing.JPanel title;
    private javax.swing.JPanel top;
    private javax.swing.JLabel usrName;
    private javax.swing.JLabel usrPoints;
    private javax.swing.JLabel usrStatus;
    // End of variables declaration//GEN-END:variables
}
