/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingPackage;

import frontEnd.BookStoreApp;

/**
 *
 * @author Julian
 */
public class OwnerHomePanel extends javax.swing.JPanel {

    
    private BookStoreApp app;
    /**
     * Creates new form OwnerHomePanel
     * @param app
     */
    public OwnerHomePanel(BookStoreApp app) {
        initComponents();
        this.app = app;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ownerContent = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        logButton = new javax.swing.JButton();
        customerManager = new javax.swing.JButton();
        bookManager = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        title.setPreferredSize(new java.awt.Dimension(402, 20));
        title.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bookstore Application v1 - Admin Homepage");
        title.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(title, java.awt.BorderLayout.PAGE_START);

        ownerContent.setLayout(new java.awt.BorderLayout());

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        logButton.setText("Logout");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        buttonPanel.add(logButton, gridBagConstraints);

        customerManager.setText("Customers");
        customerManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerManagerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        buttonPanel.add(customerManager, gridBagConstraints);

        bookManager.setText("Books");
        bookManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookManagerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        buttonPanel.add(bookManager, gridBagConstraints);

        ownerContent.add(buttonPanel, java.awt.BorderLayout.CENTER);

        add(ownerContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        app.showLogin();
    }//GEN-LAST:event_logButtonActionPerformed

    private void customerManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerManagerActionPerformed
        app.showOwnerCustomer();
    }//GEN-LAST:event_customerManagerActionPerformed

    private void bookManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookManagerActionPerformed
        app.showOwnerBook();
    }//GEN-LAST:event_bookManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookManager;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton customerManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logButton;
    private javax.swing.JPanel ownerContent;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
