/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingPackage;
import backEnd.*;
import frontEnd.BookStoreApp;
import java.util.ArrayList;
/**
 *
 * @author Julian
 */
public class OwnerCustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form OwnerCustomerPanel
     */
    public OwnerCustomerPanel(BookStoreApp app) {
        initComponents();
        this.app = app;
        refreshTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        middle = new javax.swing.JPanel();
        labelAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addCustomer = new javax.swing.JPanel();
        addName = new javax.swing.JTextField();
        addPassword = new javax.swing.JTextField();
        usrNameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        addButton = new java.awt.Button();
        addFeedback = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        bottom = new javax.swing.JPanel();
        labelAdd1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exitBook = new javax.swing.JPanel();
        labelExit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        delBook = new javax.swing.JPanel();
        delFeedback = new javax.swing.JPanel();
        delLabel = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new java.awt.BorderLayout());

        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        title.setPreferredSize(new java.awt.Dimension(402, 20));
        title.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bookstore Application v1 - Customer Manager");
        title.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(title, java.awt.BorderLayout.PAGE_START);

        content.setLayout(new java.awt.BorderLayout());

        top.setPreferredSize(new java.awt.Dimension(100, 258));
        top.setLayout(new java.awt.BorderLayout());

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Points"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        top.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        content.add(top, java.awt.BorderLayout.PAGE_START);

        middle.setPreferredSize(new java.awt.Dimension(100, 258));
        middle.setLayout(new java.awt.BorderLayout());

        labelAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAdd.setPreferredSize(new java.awt.Dimension(200, 100));
        labelAdd.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add a Customer to the database");
        labelAdd.add(jLabel2, java.awt.BorderLayout.CENTER);

        middle.add(labelAdd, java.awt.BorderLayout.LINE_START);

        addCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addCustomer.setLayout(new java.awt.GridBagLayout());

        addName.setPreferredSize(new java.awt.Dimension(300, 22));
        addName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        addCustomer.add(addName, gridBagConstraints);

        addPassword.setPreferredSize(new java.awt.Dimension(300, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        addCustomer.add(addPassword, gridBagConstraints);

        usrNameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addCustomer.add(usrNameLabel, gridBagConstraints);

        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addCustomer.add(passLabel, gridBagConstraints);

        addButton.setActionCommand("addButtonAction");
        addButton.setLabel("Confirm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 31;
        addCustomer.add(addButton, gridBagConstraints);

        addFeedback.setText("Add new User to Database");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        addCustomer.add(addFeedback, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 48;
        addCustomer.add(filler1, gridBagConstraints);

        middle.add(addCustomer, java.awt.BorderLayout.CENTER);

        content.add(middle, java.awt.BorderLayout.CENTER);

        bottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bottom.setPreferredSize(new java.awt.Dimension(12, 258));
        bottom.setLayout(new java.awt.BorderLayout());

        labelAdd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAdd1.setPreferredSize(new java.awt.Dimension(200, 100));
        labelAdd1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delete a Customer from the Database");
        labelAdd1.add(jLabel5, new java.awt.GridBagConstraints());

        jLabel6.setText("or return to Main Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        labelAdd1.add(jLabel6, gridBagConstraints);

        bottom.add(labelAdd1, java.awt.BorderLayout.LINE_START);

        exitBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exitBook.setPreferredSize(new java.awt.Dimension(400, 100));
        exitBook.setLayout(new java.awt.BorderLayout());

        labelExit.setPreferredSize(new java.awt.Dimension(100, 70));
        labelExit.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Return to Main Menu via Back Button");
        labelExit.add(jLabel7, java.awt.BorderLayout.CENTER);

        exitBook.add(labelExit, java.awt.BorderLayout.PAGE_START);

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        exitBook.add(backButton, java.awt.BorderLayout.CENTER);

        bottom.add(exitBook, java.awt.BorderLayout.LINE_END);

        delBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delBook.setLayout(new java.awt.BorderLayout());

        delFeedback.setPreferredSize(new java.awt.Dimension(100, 70));
        delFeedback.setRequestFocusEnabled(false);
        delFeedback.setLayout(new java.awt.BorderLayout());

        delLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delLabel.setText("Customer data Selected to Delete: ----none-----");
        delFeedback.add(delLabel, java.awt.BorderLayout.CENTER);

        delBook.add(delFeedback, java.awt.BorderLayout.PAGE_START);

        delButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        delButton.setText("Delete");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });
        delBook.add(delButton, java.awt.BorderLayout.CENTER);

        bottom.add(delBook, java.awt.BorderLayout.CENTER);

        content.add(bottom, java.awt.BorderLayout.PAGE_END);

        add(content, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNameActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        app.showOwnerHome();
    }//GEN-LAST:event_backButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        int[] rows = userTable.getSelectedRows();

        if (rows.length == 0) {
            delLabel.setText("Customer Selected to Delete: ----none-----");
            return;
        }

        Owner owner = new Owner();
        ArrayList<String> delUserList = new ArrayList<>();
        
        // collect selected usernames names first
        for (int row : rows) {
            String name = userTable.getValueAt(row, 0).toString();
            delUserList.add(name);
        }
        
        boolean allRemoved = true;
        
        // now delete them
        for (String name : delUserList) {
            boolean removed = owner.removeCustomer(name);
            if (!removed) {
                allRemoved = false;
            }
        }

        refreshTable();

        if (allRemoved) {
            delLabel.setText("Deleted selected user(s).");
        } else {
            delLabel.setText("Some selected users could not be deleted.");
        }
        
        
        
        
    }//GEN-LAST:event_delButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String name = addName.getText();
        String password = addPassword.getText();
        
        boolean result = false;
        result = Owner.addCustomer(name, password);
        
        if (result == true){
           addFeedback.setText("Successfully Executed.");
           refreshTable();
        }
        else{
           addFeedback.setText("Error!");
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        int[] rows = userTable.getSelectedRows();
        
        if (rows.length == 0){
            delLabel.setText("Customer Selected to Delete: ----none-----");
        } 
        else if (rows.length == 1) {
            String name = userTable.getValueAt(rows[0], 0).toString();
            delLabel.setText("Customer Selected to Delete: " + name);
        }
        else {
            delLabel.setText("Number of Customers Selected to Delete: " + rows.length);
        }
        
    }//GEN-LAST:event_userTableMouseClicked

    
    public void refreshTable(){
        customers = UserManager.getCustomers();
        
        javax.swing.table.DefaultTableModel model = 
                   (javax.swing.table.DefaultTableModel) userTable.getModel();
        
        // Clear old rows
        model.setRowCount(0);
        
        
        
        for (Customer customer : customers){
            model.addRow(new Object[]{
            customer.getName(),
            customer.getPassword(),
            customer.getPoints()
             
        });
        }
        
        
    }
    
    
    
    
    
    // Variables declaratation - Manually created
    private ArrayList<Customer> customers;
    private BookStoreApp app;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addButton;
    private javax.swing.JPanel addCustomer;
    private javax.swing.JLabel addFeedback;
    private javax.swing.JTextField addName;
    private javax.swing.JTextField addPassword;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bottom;
    private javax.swing.JPanel content;
    private javax.swing.JPanel delBook;
    private javax.swing.JButton delButton;
    private javax.swing.JPanel delFeedback;
    private javax.swing.JLabel delLabel;
    private javax.swing.JPanel exitBook;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel labelAdd;
    private javax.swing.JPanel labelAdd1;
    private javax.swing.JPanel labelExit;
    private javax.swing.JPanel middle;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPanel title;
    private javax.swing.JPanel top;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel usrNameLabel;
    // End of variables declaration//GEN-END:variables
}
