/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swingPackage;

import backEnd.*;
import frontEnd.BookStoreApp;
import java.util.ArrayList;

/**
 *
 * @author Julian
 */
public class OwnerBookPanel extends javax.swing.JPanel {
    
    
    /**
     * Creates new form OwnerBookPanel
     */
    public OwnerBookPanel(BookStoreApp app) {
        initComponents();
        this.app = app;
        
        
        
        refreshTable();
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        middle = new javax.swing.JPanel();
        labelAdd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addBook = new javax.swing.JPanel();
        addName = new javax.swing.JTextField();
        addPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addButton = new java.awt.Button();
        addFeedback = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        bottom = new javax.swing.JPanel();
        labelAdd1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exitBook = new javax.swing.JPanel();
        labelExit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        delBook = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 800));
        setLayout(new java.awt.BorderLayout());

        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        title.setPreferredSize(new java.awt.Dimension(402, 20));
        title.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bookstore Application v1");
        title.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(title, java.awt.BorderLayout.PAGE_START);

        content.setLayout(new java.awt.BorderLayout());

        top.setPreferredSize(new java.awt.Dimension(100, 258));
        top.setLayout(new java.awt.BorderLayout());

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);

        top.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        content.add(top, java.awt.BorderLayout.PAGE_START);

        middle.setPreferredSize(new java.awt.Dimension(100, 258));
        middle.setLayout(new java.awt.BorderLayout());

        labelAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAdd.setPreferredSize(new java.awt.Dimension(200, 100));
        labelAdd.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add a book to the store:");
        labelAdd.add(jLabel2, java.awt.BorderLayout.CENTER);

        middle.add(labelAdd, java.awt.BorderLayout.LINE_START);

        addBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBook.setLayout(new java.awt.GridBagLayout());

        addName.setPreferredSize(new java.awt.Dimension(300, 22));
        addName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        addBook.add(addName, gridBagConstraints);

        addPrice.setPreferredSize(new java.awt.Dimension(300, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        addBook.add(addPrice, gridBagConstraints);

        jLabel3.setText("Book Name/Label");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addBook.add(jLabel3, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Price of book");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addBook.add(jLabel4, gridBagConstraints);

        addButton.setActionCommand("addButtonAction");
        addButton.setLabel("Confirm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 31;
        addBook.add(addButton, gridBagConstraints);

        addFeedback.setText("Add book to store");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        addBook.add(addFeedback, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 48;
        addBook.add(filler1, gridBagConstraints);

        middle.add(addBook, java.awt.BorderLayout.CENTER);

        content.add(middle, java.awt.BorderLayout.CENTER);

        bottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bottom.setPreferredSize(new java.awt.Dimension(12, 258));
        bottom.setLayout(new java.awt.BorderLayout());

        labelAdd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAdd1.setPreferredSize(new java.awt.Dimension(200, 100));
        labelAdd1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delete book from store");
        labelAdd1.add(jLabel5, new java.awt.GridBagConstraints());

        jLabel6.setText("or return to Main Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        labelAdd1.add(jLabel6, gridBagConstraints);

        bottom.add(labelAdd1, java.awt.BorderLayout.LINE_START);

        exitBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exitBook.setPreferredSize(new java.awt.Dimension(400, 100));
        exitBook.setLayout(new java.awt.BorderLayout());

        labelExit.setPreferredSize(new java.awt.Dimension(100, 70));
        labelExit.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Return to Main Menu via Back Button");
        labelExit.add(jLabel7, java.awt.BorderLayout.CENTER);

        exitBook.add(labelExit, java.awt.BorderLayout.PAGE_START);
        exitBook.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        exitBook.add(backButton, java.awt.BorderLayout.CENTER);

        bottom.add(exitBook, java.awt.BorderLayout.LINE_END);

        delBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bottom.add(delBook, java.awt.BorderLayout.CENTER);

        content.add(bottom, java.awt.BorderLayout.PAGE_END);

        add(content, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNameActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        app.showOwnerHome();
    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshTable(){
        books = BookManager.getBooks();
        
        javax.swing.table.DefaultTableModel model = 
                   (javax.swing.table.DefaultTableModel) bookTable.getModel();
        
        // Clear old rows
        model.setRowCount(0);
        
        
        
        for (Book book : books){
            model.addRow(new Object[]{
            book.getName(),
            book.getPrice()
        });
        }
        
        
    }
    
    
    
    // Variables declaratation - Manually created
    private ArrayList<Book> books;
    private BookStoreApp app;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBook;
    private java.awt.Button addButton;
    private javax.swing.JLabel addFeedback;
    private javax.swing.JTextField addName;
    private javax.swing.JTextField addPrice;
    private javax.swing.JButton backButton;
    private javax.swing.JTable bookTable;
    private javax.swing.JPanel bottom;
    private javax.swing.JPanel content;
    private javax.swing.JPanel delBook;
    private javax.swing.JPanel exitBook;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel labelAdd;
    private javax.swing.JPanel labelAdd1;
    private javax.swing.JPanel labelExit;
    private javax.swing.JPanel middle;
    private javax.swing.JPanel title;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
